version: '3.8'

services:
  
  mysql:
    image: mysql:8.0
    container_name: mecaniqa-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mecaniqa_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  
  redis:
    image: redis:alpine
    container_name: mecaniqa-redis
    ports:
      - "6379:6379"


  api:
    build: .
    container_name: mecaniqa-api
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mecaniqa_db
      SPRING_REDIS_HOST: redis


volumes:
  mysql_data: