---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulador-iot-deployment
  labels:
    app: simulador-iot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulador-iot
  template:
    metadata:
      labels:
        app: simulador-iot
    spec:
      containers:
        - name: simulador-iot
          image: simulador-iot:latest # Imagem a ser gerada a partir do Dockerfile local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: simulador-iot-service
spec:
  type: ClusterIP
  selector:
    app: simulador-iot
  ports:
    - port: 8000
      targetPort: 8000
